# scan the docker file for best practices and security issues

name: Docker Lint

on:
  workflow_call:

jobs:
  validate-dokcerfile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
